# Generated by Django 6.1 on 2026-08-25 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_id', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('source', models.CharField(choices=[('authority', 'Authority'), ('internal', 'Internal audit')], max_length=20)),
                ('seq', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=80)),
                ('cls', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1)),
                ('kind', models.CharField(blank=True, choices=[('Subjective', 'Subjective'), ('Objective', 'Objective')], max_length=20)),
                ('authority', models.CharField(blank=True, max_length=120)),
                ('date_raised', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Awaiting Authority', 'Awaiting Authority'), ('Closed', 'Closed')], default='Open', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('resolution', models.TextField(blank=True)),
                ('closure_evidence', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='devices.device')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['source', 'seq'],
                'constraints': [models.UniqueConstraint(fields=('source', 'seq'), name='uniq_finding_source_seq')],
            },
        ),
    ]
