# Generated by Django 6.1 on 2026-08-25 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finding',
            options={'ordering': ['source', 'seq', 'id']},
        ),
        migrations.RemoveConstraint(
            model_name='finding',
            name='uniq_finding_source_seq',
        ),
    ]
