# Generated by Django 6.0.1 on 2026-09-22 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0002_alter_finding_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finding',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
