# Generated by Django 6.1 on 2026-08-25 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_id', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('Full Flight Simulator (FFS)', 'Full Flight Simulator (FFS)'), ('Flight Training Device (FTD)', 'Flight Training Device (FTD)'), ('Flight and Navigation Procedures Trainer (FNPT)', 'Flight and Navigation Procedures Trainer (FNPT)'), ('Basic Instrument Trainer (BITD)', 'Basic Instrument Trainer (BITD)'), ('Other', 'Other')], default='Flight and Navigation Procedures Trainer (FNPT)', max_length=80)),
                ('level', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('I', 'I'), ('II', 'II'), ('III', 'III')], max_length=8)),
                ('manufacturer', models.CharField(blank=True, max_length=120)),
                ('serial', models.CharField(blank=True, max_length=80)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('navdata_cycle', models.CharField(choices=[('3m', '3 months'), ('28d', '28 days')], default='3m', max_length=8)),
                ('maintenance_program', models.CharField(blank=True, choices=[('program_a', 'Monthly / 12-Month / 300-Hour / As Required'), ('program_b', 'Monthly / 12-Month / As Required'), ('program_c', 'Quarterly / Semester / 12-Month')], max_length=20)),
                ('current_hours_minutes', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
