# Generated by Django 6.1 on 2026-09-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='maintenance_program',
            field=models.CharField(blank=True, choices=[('program_a', 'Monthly / 12-Month / 300-Hour / 3-Year / As Required'), ('program_b', 'Monthly / 12-Month / 300-Hour / 6-Month / As Required'), ('program_c', 'Quarterly / Semester / 12-Month')], max_length=20),
        ),
    ]
