# Generated by Django 6.1 on 2026-08-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ato_name', models.CharField(default='FSTD Manager', max_length=200)),
                ('threshold_days', models.PositiveSmallIntegerField(default=30)),
                ('finding_categories', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Organization settings',
                'verbose_name_plural': 'Organization settings',
            },
        ),
    ]
