# Generated by Django 6.1 on 2026-08-25 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_key', models.CharField(max_length=40)),
                ('last_completed', models.DateField(blank=True, null=True)),
                ('next_due', models.DateField(blank=True, null=True)),
                ('last_service_hours_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_tasks', to='devices.device')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['device__name', 'task_key'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('service_hours_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='operations.maintenancetask')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PermanentDefect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_id', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('seq', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('date_noted', models.DateField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permanent_defects', to='devices.device')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['device__name', 'seq'],
            },
        ),
        migrations.CreateModel(
            name='HoldItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_id', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('seq', models.PositiveIntegerField()),
                ('atl_log_item', models.CharField(blank=True, max_length=80)),
                ('affected_version', models.CharField(blank=True, choices=[('MEP', 'MEP'), ('SEP', 'SEP'), ('BOTH', 'BOTH'), ('JET', 'JET')], max_length=8)),
                ('description', models.TextField(blank=True)),
                ('initials_report', models.CharField(blank=True, max_length=80)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('defect_category', models.CharField(blank=True, choices=[('MIN', 'Minor (90 days)'), ('MAJ', 'Major (30 days)'), ('OBS', 'Observation (no limit)')], max_length=8)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('closure_atl_log_item', models.CharField(blank=True, max_length=80)),
                ('closure_hours', models.CharField(blank=True, max_length=20)),
                ('closure_date', models.DateField(blank=True, null=True)),
                ('initials_closure', models.CharField(blank=True, max_length=80)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hold_items', to='devices.device')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['device__name', 'seq'],
                'constraints': [models.UniqueConstraint(fields=('device', 'seq'), name='uniq_hil_device_seq')],
            },
        ),
        migrations.AddConstraint(
            model_name='maintenancetask',
            constraint=models.UniqueConstraint(fields=('device', 'task_key'), name='uniq_device_task'),
        ),
        migrations.AddConstraint(
            model_name='permanentdefect',
            constraint=models.UniqueConstraint(fields=('device', 'seq'), name='uniq_perm_device_seq'),
        ),
    ]
